import os
import importlib.util
import pygame
import torch
import torch.nn as nn

# ┌───────────────────────────┐
# │ CONFIG                    │
# └───────────────────────────┘
WINDOW_W = 800
WINDOW_H = 450
TOP_H    = 400

DRAW_W   = WINDOW_W // 2      # drawing happens in LEFT half
BUTTON_H = WINDOW_H - TOP_H
BUTTON_LABELS = ["Train AI", "Draw Original", "Draw with AI", "Save Image"]

DATA_PY   = "runs_data.py"
MODEL_PTH = "stroke_model.pth"

MAX_EPOCHS        = 1500
EPOCHS_PER_FRAME  = 10


# ┌───────────────────────────┐
# │ MODEL: t -> (x,y)         │
# └───────────────────────────┘
class StrokeNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(1, 64),
            nn.Tanh(),
            nn.Linear(64, 64),
            nn.Tanh(),
            nn.Linear(64, 2),
        )

    def forward(self, t):
        return self.net(t)  # t: (T,1)


# ┌───────────────────────────┐
# │ DATA HELPERS              │
# └───────────────────────────┘
def load_runs():
    if not os.path.exists(DATA_PY):
        return []
    spec = importlib.util.spec_from_file_location("runs_data", DATA_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    runs = getattr(mod, "RUNS", [])
    cleaned = []
    for run in runs:
        seq = []
        for pt in run:
            if len(pt) != 2:
                continue
            x, y = pt
            x = min(max(float(x), 0.0), 1.0)
            y = min(max(float(y), 0.0), 1.0)
            seq.append([x, y])
        if seq:
            cleaned.append(seq)
    return cleaned


def save_runs(runs):
    with open(DATA_PY, "w") as f:
        f.write("# Auto-generated by main_ui.py\n")
        f.write("RUNS = [\n")
        for run in runs:
            f.write("    [  # one run\n")
            for x, y in run:
                f.write(f"        [{x:.6f}, {y:.6f}],  # x, y\n")
            f.write("    ],\n")
        f.write("]\n")


# ┌───────────────────────────┐
# │ MODEL UTILS               │
# └───────────────────────────┘
def load_model():
    device = torch.device("cpu")
    model = StrokeNet().to(device)
    if os.path.exists(MODEL_PTH):
        model.load_state_dict(torch.load(MODEL_PTH, map_location=device))
    model.eval()
    return model


def smooth_points(points, alpha=0.25):
    """Simple exponential smoothing so AI path looks less jagged."""
    if not points:
        return points
    smoothed = [points[0]]
    for x, y in points[1:]:
        px, py = smoothed[-1]
        sx = alpha * x + (1 - alpha) * px
        sy = alpha * y + (1 - alpha) * py
        smoothed.append([sx, sy])
    return smoothed


def generate_ai_run_from_model(model, seq_len):
    device = next(model.parameters()).device
    t = torch.linspace(0.0, 1.0, steps=seq_len, device=device).unsqueeze(1)  # (T,1)
    with torch.no_grad():
        xy = model(t).cpu().numpy()
    pts = []
    for x, y in xy:
        x = min(max(float(x), 0.0), 1.0)
        y = min(max(float(y), 0.0), 1.0)
        pts.append([x, y])
    return smooth_points(pts, alpha=0.25)


# screen coord helpers
def norm_to_screen_left(x_norm, y_norm, left_rect):
    x = int(x_norm * left_rect.width) + left_rect.left
    y = int((1.0 - y_norm) * left_rect.height) + left_rect.top
    return x, y


def norm_to_screen_right(x_norm, y_norm, right_rect):
    x = int(x_norm * right_rect.width) + right_rect.left
    y = int((1.0 - y_norm) * right_rect.height) + right_rect.top
    return x, y


# ┌───────────────────────────┐
# │ MAIN PYGAME UI            │
# └───────────────────────────┘
def main():
    pygame.init()
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    pygame.display.set_caption("Stroke AI Demo")
    clock = pygame.time.Clock()
    font = pygame.font.SysFont(None, 24)

    # bottom buttons
    btn_w = WINDOW_W // len(BUTTON_LABELS)
    buttons = []
    for i, label in enumerate(BUTTON_LABELS):
        rect = pygame.Rect(i * btn_w, TOP_H, btn_w, BUTTON_H)
        buttons.append((rect, label))

    runs = load_runs()
    status = "Draw in LEFT half, then Train AI. Use 'Save Image' button."

    state = "menu"  # menu, play_original, play_both, train
    frame_idx = 0
    play_len = 0
    current_run = None
    ai_run = None

    recording_run = []
    mouse_was_down = False

    train_ctx = None

    # screenshot stuff
    request_save = False
    save_index = 1

    running = True
    while running:
        # ── events ─────────────────────────────
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    if state == "train":
                        if train_ctx is not None and train_ctx["epoch"] >= MAX_EPOCHS:
                            # finished training, just close view
                            train_ctx = None
                            state = "menu"
                            status = "Closed training view."
                        else:
                            # cancelled early
                            train_ctx = None
                            state = "menu"
                            status = "Training cancelled."
                    elif state in ("play_original", "play_both"):
                        state = "menu"
                        status = "Playback stopped (ESC)."
                    else:
                        running = False

            elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                mx, my = event.pos
                if my >= TOP_H:
                    # bottom buttons (always clickable)
                    for (rect, label) in buttons:
                        if rect.collidepoint(mx, my):
                            if label == "Train AI":
                                if not runs:
                                    status = "Draw first in LEFT half."
                                else:
                                    ref_run = runs[-1]
                                    seq_len = len(ref_run)
                                    device = torch.device("cpu")

                                    target = torch.tensor(ref_run, dtype=torch.float32,
                                                          device=device)  # (T,2)
                                    t = torch.linspace(0.0, 1.0, steps=seq_len,
                                                       device=device).unsqueeze(1)

                                    model = StrokeNet().to(device)
                                    optim = torch.optim.Adam(model.parameters(), lr=1e-3)
                                    loss_fn = nn.MSELoss()

                                    preview_run = generate_ai_run_from_model(model, seq_len)

                                    train_ctx = {
                                        "model": model,
                                        "optim": optim,
                                        "loss_fn": loss_fn,
                                        "t": t,
                                        "target": target,
                                        "epoch": 0,
                                        "last_loss": None,
                                        "ref_run": ref_run,
                                        "preview_run": preview_run,
                                        "saved": False,
                                    }
                                    state = "train"
                                    status = "Training AI (left = original, right = AI)."
                            elif label == "Draw Original":
                                if runs:
                                    current_run = runs[-1]
                                    ai_run = None
                                    frame_idx = 0
                                    play_len = len(current_run)
                                    state = "play_original"
                                    status = "Playing original run."
                                else:
                                    status = "No runs yet. Draw first."
                            elif label == "Draw with AI":
                                if not runs:
                                    status = "No runs yet. Draw first."
                                elif not os.path.exists(MODEL_PTH):
                                    status = "No trained model. Train AI first."
                                else:
                                    current_run = runs[-1]
                                    model = load_model()
                                    ai_run = generate_ai_run_from_model(model, len(current_run))
                                    frame_idx = 0
                                    play_len = min(len(current_run), len(ai_run))
                                    state = "play_both"
                                    status = "Original (left) vs AI (right)."
                            elif label == "Save Image":
                                request_save = True

        # ── recording logic (menu, left half only) ──────
        if state == "menu":
            pressed = pygame.mouse.get_pressed()[0]
            mx, my = pygame.mouse.get_pos()

            # start drag in LEFT half of top area
            if pressed and not mouse_was_down and my < TOP_H and mx < DRAW_W:
                recording_run = []
                status = "Recording stroke... release to save."

            # while dragging in left half → add points
            if pressed and my < TOP_H and mx < DRAW_W and recording_run is not None:
                x = max(0, min(mx, DRAW_W - 1))
                y = max(0, min(my, TOP_H - 1))
                x_norm = x / float(DRAW_W)      # normalize to LEFT pane width
                y_norm = 1.0 - (y / float(TOP_H))
                recording_run.append([x_norm, y_norm])

            # release → save as run
            if (not pressed) and mouse_was_down and recording_run:
                if len(recording_run) > 10:
                    runs.append(recording_run)
                    save_runs(runs)
                    status = f"Recorded run #{len(runs)}."
                else:
                    status = "Stroke too short, not saved."
                recording_run = []

            mouse_was_down = pressed
        else:
            mouse_was_down = False

        # ── playback updates ───────────────────
        if state in ("play_original", "play_both"):
            if play_len > 0 and frame_idx < play_len - 1:
                frame_idx += 1
            # else: hold last frame; user can hit Save Image or ESC

        # ── training updates ───────────────────
        if state == "train" and train_ctx is not None:
            model = train_ctx["model"]
            optim = train_ctx["optim"]
            loss_fn = train_ctx["loss_fn"]
            t = train_ctx["t"]
            target = train_ctx["target"]
            ref_run = train_ctx["ref_run"]

            # keep updating until we hit MAX_EPOCHS
            if train_ctx["epoch"] < MAX_EPOCHS:
                for _ in range(EPOCHS_PER_FRAME):
                    if train_ctx["epoch"] >= MAX_EPOCHS:
                        break
                    optim.zero_grad()
                    pred = model(t)
                    loss = loss_fn(pred, target)
                    loss.backward()
                    optim.step()

                    train_ctx["epoch"] += 1
                    train_ctx["last_loss"] = float(loss.item())

            # update preview every frame
            train_ctx["preview_run"] = generate_ai_run_from_model(
                model, seq_len=len(ref_run)
            )

            # once finished, save model once and keep view
            if train_ctx["epoch"] >= MAX_EPOCHS and not train_ctx["saved"]:
                torch.save(model.state_dict(), MODEL_PTH)
                train_ctx["saved"] = True
                status = "Training done. Model saved. Press ESC to go back."

        # ── drawing ────────────────────────────
        screen.fill((255, 255, 255))

        left_rect = pygame.Rect(0, 0, DRAW_W, TOP_H)
        right_rect = pygame.Rect(DRAW_W, 0, DRAW_W, TOP_H)
        pygame.draw.rect(screen, (230, 230, 230), left_rect, 1)
        pygame.draw.rect(screen, (230, 230, 230), right_rect, 1)

        # live recording preview
        if state == "menu" and recording_run:
            pts = [norm_to_screen_left(x, y, left_rect) for (x, y) in recording_run]
            if len(pts) > 1:
                pygame.draw.lines(screen, (0, 0, 0), False, pts, 2)
            pygame.draw.circle(screen, (0, 0, 0), pts[-1], 6)

        # playback original
        if current_run is not None and state in ("play_original", "play_both") and play_len > 0:
            max_i = min(frame_idx, len(current_run) - 1)
            if max_i > 0:
                pts = [norm_to_screen_left(x, y, left_rect)
                       for (x, y) in current_run[:max_i + 1]]
                pygame.draw.lines(screen, (0, 0, 0), False, pts, 2)
                pygame.draw.circle(screen, (0, 0, 0), pts[-1], 8)

        # playback AI
        if ai_run is not None and state == "play_both" and play_len > 0:
            max_i = min(frame_idx, len(ai_run) - 1)
            if max_i > 0:
                pts_ai = [norm_to_screen_right(x, y, right_rect)
                          for (x, y) in ai_run[:max_i + 1]]
                pygame.draw.lines(screen, (0, 0, 255), False, pts_ai, 2)
                pygame.draw.circle(screen, (0, 0, 255), pts_ai[-1], 8)

        # training visualization
        if state == "train" and train_ctx is not None:
            ref_run = train_ctx["ref_run"]
            preview_run = train_ctx["preview_run"]

            overlay = pygame.Surface((WINDOW_W, TOP_H), pygame.SRCALPHA)
            overlay.fill((240, 240, 240, 120))
            screen.blit(overlay, (0, 0))

            if ref_run:
                pts_ref = [norm_to_screen_left(x, y, left_rect) for (x, y) in ref_run]
                if len(pts_ref) > 1:
                    pygame.draw.lines(screen, (0, 0, 0), False, pts_ref, 2)
                    pygame.draw.circle(screen, (0, 0, 0), pts_ref[-1], 8)

            if preview_run:
                pts_ai = [norm_to_screen_right(x, y, right_rect)
                          for (x, y) in preview_run]
                if len(pts_ai) > 1:
                    pygame.draw.lines(screen, (0, 0, 255), False, pts_ai, 2)
                    pygame.draw.circle(screen, (0, 0, 255), pts_ai[-1], 8)

            epoch = train_ctx["epoch"]
            loss_val = train_ctx["last_loss"]

            bar_margin = 50
            bar_width = WINDOW_W - 2 * bar_margin
            bar_height = 8
            bar_x = bar_margin
            # moved ~0.5 inch lower (≈ +50 px)
            bar_y = TOP_H // 2 + 60 + 50

            pygame.draw.rect(screen, (200, 200, 200),
                             (bar_x, bar_y, bar_width, bar_height))
            progress = epoch / float(MAX_EPOCHS)
            prog_w = int(bar_width * progress)
            pygame.draw.rect(screen, (100, 200, 100),
                             (bar_x, bar_y, prog_w, bar_height))

            txt1 = font.render(f"Training AI: epoch {epoch}/{MAX_EPOCHS}", True, (0, 0, 0))
            screen.blit(txt1, (bar_x, bar_y - 60))
            if loss_val is not None:
                txt2 = font.render(f"Loss: {loss_val:.6f}", True, (0, 0, 0))
                screen.blit(txt2, (bar_x, bar_y - 30))
            txt3 = font.render("Left: original run  |  Right: current AI prediction",
                               True, (0, 0, 0))
            screen.blit(txt3, (bar_x, bar_y + 20))

        # buttons
        for rect, label in buttons:
            pygame.draw.rect(screen, (200, 200, 200), rect)
            pygame.draw.rect(screen, (0, 0, 0), rect, 2)
            txt = font.render(label, True, (0, 0, 0))
            screen.blit(txt, txt.get_rect(center=rect.center))

        # status
        status_surf = font.render(status, True, (0, 0, 0))
        screen.blit(status_surf, (10, TOP_H - 30))

        # ── handle screenshot request (after drawing) ─────
        if request_save:
            top_rect = pygame.Rect(0, 0, WINDOW_W, TOP_H)
            surf = screen.subsurface(top_rect).copy()
            fname = f"comparison_{save_index:02d}.png"
            try:
                pygame.image.save(surf, fname)
                status = f"Saved image: {fname}"
                save_index += 1
            except Exception as e:
                status = f"Failed to save image: {e}"
            request_save = False

        pygame.display.flip()
        clock.tick(60)

    pygame.quit()

    # cleanup data + model (keep images)
    for fname in [DATA_PY, MODEL_PTH]:
        if os.path.exists(fname):
            try:
                os.remove(fname)
            except Exception:
                pass


if __name__ == "__main__":
    main()